### ISSUE TITLE
Crash repport

### ISSUE THREAD

**Issue by Heriptik** [zlainsama/OfflineSkins#24]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  offlineskins (OfflineSkins-1.12.2-v4-core.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 8/2/18 2:31 PM
Description: Tesselating block model

java.lang.OutOfMemoryError: Tesselating block model
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:41)
	at net.minecraft.client.renderer.BufferBuilder.func_181670_b(BufferBuilder.java:101)
	at net.minecraft.client.renderer.BufferBuilder.func_178981_a(BufferBuilder.java:605)
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:202)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:116)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:79)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:58)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:328)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Unknown Source)

**Comment by zlainsama** [comment]
It says right there: "OutOfMemoryError".
And my mod "OfflineSkins" does not have anything to do with tesselating block model.
