### ISSUE TITLE
1.12.2 crash 

### ISSUE THREAD

**Issue by KrauzeBartek** [zlainsama/OfflineSkins#28]
Description: Rendering item

java.lang.NoSuchMethodError: lain.mods.skins.init.forge.ForgeOfflineSkins.getSkinWidth(Lnet/minecraft/util/ResourceLocation;)I
    at lain.mods.skins.init.forge.asm.Hooks.getSkinWidth(Hooks.java:58)
    at net.minecraft.client.renderer.tileentity.TileEntitySkullRenderer.renderSkull(SourceFile:90)
    at net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer.renderByItem(TileEntityItemStackRenderer.java:104)
    at net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer.renderByItem(TileEntityItemStackRenderer.java:45)
    at reborncore.shields.client.RebornItemStackRenderer.renderByItem(RebornItemStackRenderer.java:116)
    at net.minecraft.client.renderer.RenderItem.renderItem(RenderItem.java:198)
    at net.minecraft.client.renderer.RenderItem.renderItemModelIntoGUI(RenderItem.java:517)
    at net.minecraft.client.renderer.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:559)
    at codechicken.lib.render.item.CCRenderItem.renderItemAndEffectIntoGUI(CCRenderItem.java:356)
    at net.minecraft.client.gui.inventory.GuiContainer.drawSlot(GuiContainer.java:265)
    at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:98)
    at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:51)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:643)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at sun.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1456)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by zlainsama** [comment]
It looks like you are updating the mod to a newer version, you need to delete outdated coremods used by this mod.
It is located in mods/1.12.2.
Sorry for the inconvenience, the whole coremod system is changed in 1.13, which will no longer required to be in a separate jar, so i'm not bothered to update this in 1.12, just delete outdated coremods, you will be fine.

**Comment by KrauzeBartek** [comment]
Thanks ! Close issue.
