### ISSUE TITLE
Cursed Textures

### ISSUE THREAD

**Issue by SymbolKlar** [zlainsama/OfflineSkins#62]
Entering the game the textures are fine at the start, but after playing for a long period of time without restarting, or, reloading resourcepacks (either f3+t or changing one through the menu) the textures warp out and back into existence. As seen in the video. I can provide other details when prompted so I am leaving the report as this for now.

https://youtu.be/LHUkRjCnz00

**Comment by Hezaus** [comment]
Kinda the same issue here but instead of the resource pack being affected only the skin I am using is affected, other players ( That are using cracked from my experience ) don't. I don't know how this could be caused but first, the skin actually loads but just for a few minutes, it changes back to gmod missing texture, and then a few minutes more it changes back to Minecraft default skin in my case it is always Sunny skin ( Which is the same things on the server without the mod on ). There are times that it doesn't change into the gmod missing texture but with the default skin, it varies. But when it changes to the default skin it stays as default from my experience.

The error
```log
[21:40:36] [Render thread/WARN]: Failed to load texture: offlineskins:textures/generated/f1bb2670-8b31-4e5c-86dd-cac3e1bc1e5d
java.io.FileNotFoundException: offlineskins:textures/generated/f1bb2670-8b31-4e5c-86dd-cac3e1bc1e5d
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_18153(class_1049.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_4625(class_1049.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java:118) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668$class_4683.method_23563(class_4668.java:243) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
	at net.minecraft.class_1921$class_4687.method_23595(class_1921.java:1086) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.method_22993(FullyBufferedMultiBufferSource.java:136) ~[iris-mc1.20.2-1.6.9.jar:?]
	at net.minecraft.class_761.handler$dad000$iris$batchedentityrendering$beginTranslucents(class_761.java:3684) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1261) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1113) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:881) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[client-1.20.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
```

I use mods but I don't think that there should be any mods that caused it other than the 3d skin layer which is unlikely
It does show Iris in the error but when I disable it and come back the error still occurs.
Mods:
```log
[21:59:38] [main/INFO]: Loading 222 mods:
	- ambientenvironment 12.0.0.2
	- ambientsounds 5.2.23
	- appleskin 2.5.1+mc1.20.2
	- architectury 10.0.8
	- autohud 6.2+1.20.2
	- axiom 1.4.1
	   \-- com_moulberry_axiomclientapi_axiomclientapi_ 1.0.0
	- betterclouds 1.4.1+1.20.2
	- bettermounthud 1.2.2
	- betterstats 3.1+fabric-1.20.2
	   \-- tcdcommons 3.1+fabric-1.20.2
	- betterthirdperson 1.9.0
	- blahaj-totem 1.0.0
	- blur 3.1.1
	   |-- midnightlib 1.5.0
	   \-- satin 1.14.0
	- boatiview 0.0.5
	- bobby 5.0.2
	   |-- com_typesafe_config 1.4.2
	   |-- io_leangen_geantyref_geantyref 1.3.13
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- borderlessmining 1.1.8+1.20.1
	- cameraoverhaul 1.4.0-fabric-universal
	- camerautils 1.20.2-1.0.5
	- cat_jam 1.2.1
	- chat_heads 0.10.22
	- chunksfadein 1.0.0-1.20.2
	   |-- com_moandjiezana_toml_toml4j 0.7.2
	   \-- crowdin-translate 1.4+1.19.3
	- chunky 1.3.92
	- cleardespawn 1.1.13
	- cloth-config 12.0.109
	   \-- cloth-basic-math 0.6.1
	- clumps 13.0.0.1
	- collective 6.66
	- continuity 3.0.0-beta.4+1.20.2
	- controlify 1.7.0-beta.2+1.20
	   |-- dev_isxander_libsdl4j 2.28.2-11
	   |-- org_hid4java_hid4java 0.7.0
	   \-- org_quiltmc_quilt-json5 1.0.3
	- controlling 13.0.1
	- creativecore 2.11.2
	   \-- net_minecraftforge_eventbus 6.0.3
	- debugify 1.20.2+1.0
	- detailab 2.6.3+1.20.2-fabric
	- draggable_lists 1.0.2
	- dynamic_fps 3.2.1
	- dynamiccrosshair 7.3+1.20.2
	   \-- yaclx 1.6+1.20
	- e4mc_minecraft 4.0.1
	- eatinganimationid 1.9.4+1.20
	- entity_model_features 1.0.2
	- entity_texture_features 4.5.1
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.2-mc1.20.1
	- euphoria_patcher 0.1.2-fabric
	   \-- io_sigpipe_jbsdiff 1.0
	- extremesoundmuffler 3.41-fabric-1.20.2
	   \-- fiber 0.23.0-2
	- fabric-api 0.89.3+1.20.2
	   |-- fabric-api-base 0.4.33+fce67b32a0
	   |-- fabric-api-lookup-api-v1 1.6.41+fce67b32a0
	   |-- fabric-biome-api-v1 13.0.12+d9a2869ba0
	   |-- fabric-block-api-v1 1.0.12+73761d2ea0
	   |-- fabric-block-view-api-v2 1.0.1+73761d2ea0
	   |-- fabric-blockrenderlayer-v1 1.1.43+f4b7e424a0
	   |-- fabric-client-tags-api-v1 1.1.4+86b12645a0
	   |-- fabric-command-api-v1 1.2.36+f71b366fa0
	   |-- fabric-command-api-v2 2.2.15+86b12645a0
	   |-- fabric-commands-v0 0.2.53+df3654b3a0
	   |-- fabric-containers-v0 0.1.72+df3654b3a0
	   |-- fabric-content-registries-v0 5.0.4+285022b3a0
	   |-- fabric-convention-tags-v1 1.5.7+f4b7e424a0
	   |-- fabric-crash-report-info-v1 0.2.20+f4b7e424a0
	   |-- fabric-data-generation-api-v1 13.1.2+d19c4129a0
	   |-- fabric-dimensions-v1 2.1.56+b1229956a0
	   |-- fabric-entity-events-v1 1.5.25+f4b7e424a0
	   |-- fabric-events-interaction-v0 0.6.9+daef22a2a0
	   |-- fabric-events-lifecycle-v0 0.2.68+df3654b3a0
	   |-- fabric-game-rule-api-v1 1.0.40+f4b7e424a0
	   |-- fabric-item-api-v1 2.1.32+43511215a0
	   |-- fabric-item-group-api-v1 4.0.13+f4b7e424a0
	   |-- fabric-key-binding-api-v1 1.0.38+f4b7e424a0
	   |-- fabric-keybindings-v0 0.2.36+df3654b3a0
	   |-- fabric-lifecycle-events-v1 2.2.26+3bafade3a0
	   |-- fabric-loot-api-v2 2.0.2+0ba8e9cea0
	   |-- fabric-message-api-v1 6.0.1+e982ae85a0
	   |-- fabric-mining-level-api-v1 2.1.54+f4b7e424a0
	   |-- fabric-model-loading-api-v1 1.0.5+f4b7e424a0
	   |-- fabric-models-v0 0.4.4+9386d8a7a0
	   |-- fabric-networking-api-v1 3.0.8+b18afef3a0
	   |-- fabric-object-builder-api-v1 12.1.1+b1b4f7b0a0
	   |-- fabric-particles-v1 1.1.4+f4b7e424a0
	   |-- fabric-recipe-api-v1 2.0.5+96509552a0
	   |-- fabric-registry-sync-v0 4.0.3+34a3e0e2a0
	   |-- fabric-renderer-api-v1 3.2.1+2034447ca0
	   |-- fabric-renderer-indigo 1.5.1+2034447ca0
	   |-- fabric-renderer-registries-v1 3.2.48+df3654b3a0
	   |-- fabric-rendering-data-attachment-v1 0.3.39+73761d2ea0
	   |-- fabric-rendering-fluids-v1 3.0.30+f4b7e424a0
	   |-- fabric-rendering-v0 1.1.51+df3654b3a0
	   |-- fabric-rendering-v1 3.0.10+86b12645a0
	   |-- fabric-resource-conditions-api-v1 2.3.9+43511215a0
	   |-- fabric-resource-loader-v0 0.11.11+86b12645a0
	   |-- fabric-screen-api-v1 2.0.11+0ba8e9cea0
	   |-- fabric-screen-handler-api-v1 1.3.38+86b12645a0
	   |-- fabric-sound-api-v1 1.0.14+f4b7e424a0
	   |-- fabric-transfer-api-v1 3.3.8+109a65e5a0
	   \-- fabric-transitive-access-wideners-v1 5.0.3+fce67b32a0
	- fabric-language-kotlin 1.10.10+kotlin.1.9.10
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.10
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.22.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.0
	- fabricloader 0.14.22
	- fabricskyboxes 0.7.3+mc1.20.2
	- fabrishot 1.10.0
	- fadeless 1.0.1
	- fallingleaves 1.15.3
	- fastquit 3.0.0+1.20+
	- ferritecore 6.0.0
	- firstperson 2.2.3
	- flash 2.0.0
	   |-- com_github_krlite_equator-v2_animation 2.6.0-mc1.20
	   \-- com_github_krlite_equator-v2_visual 2.6.0-mc1.20
	- footprintparticle 0.3.4-mc1.20.2
	- fpsreducer 1.20.2-2.6
	- freecam 1.2.1.1+1.20
	- fsb-interop 1.3.5+mc1.20.2-build.49
	- fusion 1.0.6
	- immediatelyfast 1.2.6+1.20.2
	   |-- com_github_llamalad7_mixinextras 0.2.0-rc.5
	   \-- net_lenni0451_reflect 1.2.4
	- indium 1.0.27+mc1.20.1
	- inventoryprofilesnext 1.10.7
	- isxander-main-menu-credits 1.1.2
	- itemswapper 0.5.3-mc1.20.2
	- java 17
	- jump_sounds 1.4.2
	- lambdynlights 2.3.2+1.20.1
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.0+1.20
	- languagereload 1.5.9+1.20.2
	   \-- com_github_llamalad7_mixinextras 0.2.0-rc.5
	- libipn 4.0.0
	- lithium 0.12.0
	- make_bubbles_pop 0.2.0-fabric
	- minecraft 1.20.2
	- mixintrace 1.1.1+1.17
	- modelfix 1.14
	- modernfix 5.7.5+mc1.20.2
	- modmenu 8.0.0
	- morechathistory 1.1.1
	- moreculling 1.20.1-0.19.0
	   \-- conditional-mixin 0.3.2
	- mousetweaks 2.25
	- mousewheelie 1.13.2+mc1.20.2
	   |-- amecsapi 1.5.5+mc1.20.2
	   |-- coat 1.0.0-beta.21+mc1.20.2
	   |-- tweed4_annotated 1.3.1+mc1.20.2
	   |-- tweed4_base 1.7.1+mc1.20.2
	   |-- tweed4_data 1.2.1+mc1.20.2
	   |-- tweed4_data_hjson 1.1.1+mc1.20.2
	   |-- tweed4_tailor_coat 1.1.3+mc1.20.2
	   |-- tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20.2
	   \-- tweed4_tailor_screen 1.1.4+mc1.20.2
	- nochatreports 1.20.2-v2.3.1
	- notenoughanimations 1.6.4
	- offlineskins 1.20.2-v1-fabric
	- particlerain 2.0.7
	- particletweaks 1.1.3-Fabric+1.20.2-unstable
	- physicsmod 3.0.9
	- puzzle 1.6.0+1.20.2
	   |-- midnightlib 1.5.0
	   |-- puzzle-base 1.6.0+1.20.2
	   |-- puzzle-gui 1.6.0+1.20.2
	   |-- puzzle-models 1.6.0+1.20.2
	   \-- puzzle-splashscreen 1.6.0+1.20.2
	- realcamera 0.5.3-beta
	- reeses-sodium-options 1.6.5+mc1.20.2-build.96
	- rrls 3.2.1-1.20.2-fabric
	- screenfx 1.3.2+1.20.2
	- seamless 2.1.0
	- searchables 1.0.2
	- servercountryflags 1.8.2
	- shulkerboxtooltip 4.0.5+1.20.2
	- skinlayers 1.5.6-mc1.20.2
	- smoke_suppression 1.0.17
	   \-- crowdin-translate 1.4+1.19.3
	- sodium 0.5.3
	- sodium-extra 0.5.2+mc1.20.2-build.113
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- sspb 3.2.1
	- starlight 1.1.2+fabric.bdaeb21
	- status-effect-bars 1.0.4
	- tia 1.20-1.1
	- villagernames 5.2
	- visuality 0.7.1+1.20
	- visualizerbookshelf 2.0
	- wakes 0.2.0
	   \-- blue_endless_jankson 1.2.2
	- xaerominimap 23.8.2
	- xaeroworldmap 1.34.1
	- yet_another_config_lib_v3 3.2.1+1.20.2
	   |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- yosbr 0.1.2
	- zoomify 2.12.0
	   |-- com_akuleshov7_ktoml-core-jvm 0.5.0
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   \-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6
```

If the error happens it won't fix and continue to happen and it only error 2 times and the error in the iris is different

```log
[22:00:37] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.'
[22:00:37] [Render thread/WARN]: Failed to load texture: offlineskins:textures/generated/48d676c7-145d-446b-8fb5-8e4f324cd4af
java.io.FileNotFoundException: offlineskins:textures/generated/48d676c7-145d-446b-8fb5-8e4f324cd4af
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_18153(class_1049.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_4625(class_1049.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java:118) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668$class_4683.method_23563(class_4668.java:243) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
	at net.minecraft.class_1921$class_4687.method_23595(class_1921.java:1086) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_1921.method_23012(class_1921.java:871) ~[client-intermediary.jar:?]
	at fabric.net.raphimc.immediatelyfast.feature.core.BatchableImmediate._draw(BatchableImmediate.java:38) ~[ImmediatelyFast-1.2.6+1.20.2.jar:?]
	at fabric.net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.method_22994(ImmediateAdapter.java:120) ~[ImmediatelyFast-1.2.6+1.20.2.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601) ~[?:?]
	at fabric.net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.method_37104(ImmediateAdapter.java:93) ~[ImmediatelyFast-1.2.6+1.20.2.jar:?]
	at fabric.net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.method_22994(ImmediateAdapter.java:112) ~[ImmediatelyFast-1.2.6+1.20.2.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1099) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1113) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:881) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[client-1.20.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
```
```log
[22:01:07] [Render thread/WARN]: Failed to load texture: offlineskins:textures/generated/48d676c7-145d-446b-8fb5-8e4f324cd4af
java.io.FileNotFoundException: offlineskins:textures/generated/48d676c7-145d-446b-8fb5-8e4f324cd4af
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_18153(class_1049.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_4625(class_1049.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java:118) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668$class_4683.method_23563(class_4668.java:243) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
	at net.minecraft.class_1921$class_4687.method_23595(class_1921.java:1086) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_1921.method_23012(class_1921.java:871) ~[client-intermediary.jar:?]
	at fabric.net.raphimc.immediatelyfast.feature.core.BatchableImmediate._draw(BatchableImmediate.java:38) ~[ImmediatelyFast-1.2.6+1.20.2.jar:?]
	at fabric.net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.method_22994(ImmediateAdapter.java:120) ~[ImmediatelyFast-1.2.6+1.20.2.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601) ~[?:?]
	at fabric.net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.method_37104(ImmediateAdapter.java:93) ~[ImmediatelyFast-1.2.6+1.20.2.jar:?]
	at fabric.net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.method_22994(ImmediateAdapter.java:112) ~[ImmediatelyFast-1.2.6+1.20.2.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1099) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1113) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:881) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[client-1.20.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
```

I am scared of sharing my own full logs because there may be something that I haven't stripped away also there may be some misinformation because I haven't fully played with it for a long time yet.

Turning off immediatelyfast still shows the same result but errors are now different.
```log
[22:15:08] [Render thread/WARN]: Failed to load texture: offlineskins:textures/generated/59f2093d-14f4-4186-aaf0-82351e8751e6
java.io.FileNotFoundException: offlineskins:textures/generated/59f2093d-14f4-4186-aaf0-82351e8751e6
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_18153(class_1049.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_4625(class_1049.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java:118) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668$class_4683.method_23563(class_4668.java:243) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
	at net.minecraft.class_1921$class_4687.method_23595(class_1921.java:1086) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_1921.method_23012(class_1921.java:871) ~[client-intermediary.jar:?]
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_4597$class_4598.getBuffer(class_4597.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_970.method_23192(class_970.java:118) ~[client-intermediary.jar:?]
	at net.minecraft.class_970.method_4169(class_970.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_970.method_17157(class_970.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_970.method_4199(class_970.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.class_922.method_4054(class_922.java:144) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_4215(class_1007.java:67) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_3936(class_1007.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22977(class_761.java:1342) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.handler$cgi000$firstperson$render(class_761.java:7650) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1097) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1113) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:881) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[client-1.20.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
```

**Comment by Hezaus** [comment]
Maybe related https://github.com/zlainsama/OfflineSkins/issues/60#issuecomment-1196142014 but the server property offline mode is false and it does show at first but only a minute less
